djapp/urls.py
from django.conf.urls import url
from . import views

app_name = 'djapp'

urlpatterns = [
    url(r'^$', views.ItemListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', views.ItemDetailView.as_view(), name='detail'),
]

djorm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.IndexPage.as_view(), name='index'),
    url(r'^items/', include('djapp.urls', namespace='items')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djapp/models.py
from django.db import models


# Create your models here.
class Item(models.Model):
    id = models.PositiveIntegerField(primary_key=True)
    name = models.CharField(max_length=80, unique=True, null=False)
    price = models.DecimalField(max_digits=8, decimal_places=2, null=False)
    description = models.TextField(null=False)
    image = models.ImageField(upload_to='items_images',  unique=True, null=False)

    def __str__(self):
        return str(self.id) + " : " + self.name + " : " + str(self.price)

djapp/views.py
# from django.shortcuts import render
from django.views.generic import (ListView, DetailView)  # View,TemplateView, CreateView,DeleteView, UpdateView

from . import models


# Create your views here.

class ItemListView(ListView):
    model = models.Item


class ItemDetailView(DetailView):
    model = models.Item

djorm/views.py
from django.views.generic import TemplateView


class IndexPage(TemplateView):
    template_name = 'index.html'

djapp/templates/djapp/item_detail.html
{% extends 'base.html'  %}

{% block content %}
<h1> ОПИСАНИЕ РЕШЕНИЯ </h1>
    <div class="col-md-8">
        <h3>
            № &nbsp; {{ item.id }} &nbsp;
            название: &nbsp;  <a href="{% url 'djapp:detail' pk=item.id %}">{{ item.name }}</a> &nbsp;
            цена: {{ item.price }}
        </h3>
        <p>{{item.description}}</p>
        <img src="{{ item.image.url }}" alt="Embedded Image" style="height:400px;"/>
        <hr>
    </div>
{% endblock %}

djapp/templates/djapp/item_list.html
{% extends 'base.html'  %}

{% block content %}
<h1>СПИСОК РЕШЕНИЙ</h1>
    <div class="col-md-8">
        {% for item in item_list %}
            <h3>
                № &nbsp; {{ item.id }} &nbsp;
                название: &nbsp;  <a href="{% url 'djapp:detail' pk=item.id %}">{{ item.name }}</a> &nbsp;
                цена: {{ item.price }}
            </h3>
            <img src="{{ item.image.url }}" alt="Embedded Image" style="height:50px;"/>
            <hr>
         {% endfor %}
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Ломбард</title>
    <!-- Latest Bootstrap 3.7 compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <!-- Google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static '/css/layout.css' %}">

</head>
<body>
    <nav class="navbar  mynav" role="navigation" id="navbar">
    	<div class="container">
            <a class="navbar-brand mynav" href="{% url 'index' %}">Главная страница</a>
    		<ul class="nav navbar-nav navbar-right">
    			    <li><a href="{% url 'djapp:list' %}" class="btn btn-simple">Список решений</a></li>
                    <li><a href="#" class="btn btn-simple">Залогнуть</a></li>
                    <li><a href="#" class="btn btn-simple">Вписаться</a></li>
    		</ul>
    	</div>
    </nav>
    <div class="container mycontent">
          {% block content %}
          {% endblock %}
    </div>
</body>

</html>

templates/index.html
{% extends 'base.html'  %}
{% load static from staticfiles %}

{% block content %}
<h1> ГЛАВНАЯ СТРАНИЦА</h1>
<img src="{% static 'pics/main_page.jpg' %}"  alt="Main Image" style="height:600px;"  />

{% endblock %}